services:
  prometheus:
    ports:
      - "9090:9090"
  alertmanager:
    ports:
      - "9093:9093"
  grafana:
    ports:
      - "3000:3000"
  loki:
    ports:
      - "3100:3100"
  node-exporter:
    ports:
      - "9100:9100"
  cadvisor:
    ports:
      - "8081:8080"
