global:
  scrape_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  # Backend API metrics
  - job_name: 'backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:8000']

  # Inference service metrics (dev uses 8080; include both for portability)
  - job_name: 'inference'
    metrics_path: /metrics
    static_configs:
      - targets: ['ml-inference:8000', 'ml-inference:8080']

  # Trainer (optional) — enable if trainer exposes /metrics
  - job_name: 'trainer'
    metrics_path: /metrics
    static_configs:
      - targets: ['trainer:8000']

  # Kafka via JMX exporter (javaagent) or standalone kafka-exporter
  - job_name: 'kafka-jmx'
    static_configs:
      - targets: ['kafka:7071']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']

  # Redis exporter (standard port 9121)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # MongoDB exporter (commonly 9216)
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']

  # Node exporter (host/system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor (container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
