apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app
  labels:
    app.kubernetes.io/name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
    spec:
      containers:
        - name: backend
          image: your-registry/backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: APP_ENV
              value: production
            - name: KAFKA_BROKERS
              value: kafka.data.svc.cluster.local:9092
            - name: MONGO_URI
              value: mongodb://mongo.data.svc.cluster.local:27017/fraud_db
            - name: REDIS_CLUSTER_NODES
              value: redis.data.svc.cluster.local:6379
            - name: USE_GUNICORN
              value: "true"
            - name: GUNICORN_WORKERS
              value: "4"
            - name: ENABLE_MTLS
              value: "true"
          readinessProbe:
            httpGet:
              path: /admin/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /admin/health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: app
  labels:
    app.kubernetes.io/name: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP

