version: "3.9"
services:
  backend:
    volumes:
      - ../backend:/app
      - ../models:/app/models
    environment:
      - APP_ENV=development
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload --app-dir /app

